import { FaWifi, FaCoffee, FaSnowflake, FaParking, FaSwimmingPool, FaHotdog, FaStopwatch, FaCocktail } from 'react-icons/fa';
import images from '../assets';

export const roomData = [
  {
    id: 1,
    name: 'PODDY Coffee District 1',
    description: 'Comfortable and quiet workspace in the center of District 1.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Modern Parking', icon: FaParking },
    ],
    district: 'District 1',
    address: '123 Nguyen Hue, District 1, Ho Chi Minh City',
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: 'PODDY Coffee District 3',
    description: 'Creative and dynamic space in District 3 area.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Morden Parking', icon: FaParking },
    ],
    district: 'District 3',
    address: '456 Le Van Sy, District 3, Ho Chi Minh City',
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: 'PODDY Coffee District 5',
    description: 'Quiet study and work space in District 5.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Morden Parking', icon: FaParking },
    ],
    district: 'District 5',
    address: '789 Tran Hung Dao, District 5, Ho Chi Minh City',
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: 'PODDY Coffee District 7',
    description: 'Modern and convenient space in Phu My Hung area.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Morden Parking', icon: FaParking },
    ],
    district: 'District 7',
    address: '101 Nguyen Duc Canh, District 7, Ho Chi Minh City',
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: 'PODDY Coffee District 2',
    description: 'Green and airy workspace in Thao Dien.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Morden Parking', icon: FaParking },
    ],
    district: 'District 2',
    address: '234 Nguyen Van Huong, District 2, Ho Chi Minh City',
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: 'PODDY Coffee Binh Thanh',
    description: 'Creative and dynamic space in Binh Thanh area.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Coffee', icon: FaCoffee },
      { name: 'Air Conditioning', icon: FaSnowflake },
      { name: 'Morden Parking', icon: FaParking },
    ],
    district: 'Binh Thanh',
    address: '567 Xo Viet Nghe Tinh, Binh Thanh, Ho Chi Minh City',
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
];
