export { default as Home } from './Home';
export { default as StoreDetails } from './StoreDetails';
export { default as About } from './About';
export { default as Solutions } from './Solutions';
export { default as Places } from './Places';
export { default as Contact } from './Contact';
export { default as PodDetails } from './PodDetails';
export { default as BookingHistory } from './BookingHistory';
export { default as AuthPage } from './AuthPage';
